version: "3"
##como se trata de um teste pode-se utilizar o usuario root nas configuracoes de banco ou criar um user especifico
services:
    app:
        build: 
            context: ./
        container_name: app
        environment:
          - DATABASE_HOST=db
          - DATABASE_PORT=3306
          - DATABASE_DB=db
          - DATABASE_USER=
          - DATABASE_PASS=
          - DATABASE_CHARSET=utf-8
        tty: true
        networks:
          - desafio-network
        ports:
          - 8080:80
        
    db:
        image: mariadb
        command: --innodb-use-native-aio=0
        container_name: db
        restart: always
        tty: true
        ports: 
            - 3307:3306
        volumes:
            - ./src/DB:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=db
            - MYSQL_ROOT_PASSWORD=root 
        networks:
          - desafio-network

networks:
    desafio-network:
        driver: bridge
